# Generated by Django 5.1.4 on 2025-01-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_info', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('video_link', models.CharField(blank=True, max_length=599, null=True, unique=True)),
            ],
        ),
    ]
