# Generated by Django 5.1.4 on 2025-01-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=599, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='query',
            name='video_link',
        ),
        migrations.AddField(
            model_name='query',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
