# Generated by Django 5.1.4 on 2025-01-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_videolink_remove_query_video_link_query_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolink',
            name='link',
        ),
        migrations.AddField(
            model_name='query',
            name='link',
            field=models.CharField(blank=True, max_length=599, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='videolink',
            name='links',
            field=models.ManyToManyField(related_name='video_linkss', to='query.query'),
        ),
    ]
