# Generated by Django 5.1.4 on 2025-01-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_remove_videolink_link_query_link_videolink_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='link',
        ),
        migrations.RemoveField(
            model_name='videolink',
            name='links',
        ),
        migrations.AddField(
            model_name='query',
            name='link',
            field=models.ManyToManyField(blank=True, related_name='querise', to='query.videolink'),
        ),
        migrations.AddField(
            model_name='videolink',
            name='links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
