# Generated by Django 5.1.4 on 2025-01-24 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_remove_query_link_remove_videolink_links_query_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='link',
        ),
        migrations.RemoveField(
            model_name='videolink',
            name='links',
        ),
        migrations.AddField(
            model_name='videolink',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videolink',
            name='query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_links', to='query.query'),
        ),
    ]
