# Generated by Django 5.1.4 on 2025-01-09 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.CharField(max_length=599)),
                ('project_zip', models.FileField(blank=True, null=True, upload_to='project_data')),
                ('project_link', models.CharField(default=None, max_length=1000)),
                ('project_stars', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_upload', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
