name: Deploy on AWS
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/projecthub:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/projecthub:latest

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AWS_EC2_IP }} >> ~/.ssh/known_hosts

      - name: Deploy on AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_EC2_IP }} << 'EOF'
          echo "Starting deployment..."
          
          # Login to Docker Hub
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
          # Pull latest image
          echo "Pulling latest image..."
          docker pull ${{ secrets.DOCKER_USERNAME }}/projecthub:latest
          
          # Stop and remove existing container
          echo "Stopping existing container..."
          docker stop projecthub 2>/dev/null || true
          docker rm projecthub 2>/dev/null || true
          
          # Clean up unused images
          echo "Cleaning up unused Docker images..."
          docker image prune -f
          
          # Run new container
          echo "Starting new container..."
          docker run -d \
            --name projecthub \
            -p 80:8000 \
            --restart unless-stopped \
            ${{ secrets.DOCKER_USERNAME }}/projecthub:latest
          
          # Verify deployment
          echo "Verifying deployment..."
          docker ps | grep projecthub
          echo "Deployment completed!"
          EOF